from_latest_tag = false
ignore_merge_commits = true
branch_whitelist = ["main"]
skip_ci = "[skip ci]"
pre_bump_hooks = ["mise run rust:ci"]
post_bump_hooks = []

[changelog]
template = "remote"
remote = "github.com"
repository = "build-my-own-shell"
owner = "vancanhuit"
authors = []

[git_hooks.commit-msg]
script = "mise exec -- cog verify --file $1"

[git_hooks.pre-push]
script = "mise run rust:ci"
